# Generated by Django 4.0.6 on 2022-08-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBackClass',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('mail', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('msg', models.TextField()),
                ('fid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField()),
            ],
        ),
    ]
